In [1]:
using Pkg; Pkg.activate("."); Pkg.instantiate()

 Activating environment at `/tmpdir/notebook/Project.toml`


# Chapter 3 - 数学のおさらい

## 3.1
### 3.1.1 スカラーとベクトル

In [2]:
# 列ベクトル: 2行1列のArrayを定義
# Juliaはcolumn-major
w = [5.0, 3.0]


# 行ベクトル

2-element Array{Float64,1}:
 5.0
 3.0

In [3]:
# 行ベクトル: 1行2列
x = [5.0 3.0]

1×2 Array{Float64,2}:
 5.0  3.0

In [4]:
# すべての要素が0の1行5列のArrayを生成
x_zeros = zeros(1, 5)

1×5 Array{Float64,2}:
 0.0  0.0  0.0  0.0  0.0

In [5]:
# すべての要素が1の1行5列のArrayを生成
x_ones = ones(1, 5)

1×5 Array{Float64,2}:
 1.0  1.0  1.0  1.0  1.0

In [6]:
# 一様分布または正規分布にしたがってランダムに1行5列のArrayを生成
using Random
Random.seed!(1234)

# 一様分布
uniform = rand(1, 5)

1×5 Array{Float64,2}:
 0.590845  0.766797  0.566237  0.460085  0.794026

In [7]:
# 正規分布
normal = randn(1, 5)

1×5 Array{Float64,2}:
 2.21188  0.532813  -0.271735  0.502334  -0.516984

In [8]:
# 標準出力
for s in (:w, :x, :x_zeros, :x_ones, :uniform, :normal)
    y = eval(s)
    println("ベクトル $(s)) 形: $(size(y)), 型:$(eltype(y))\n$(y)\n")
end


### 3.1.2 ベクトルの内積
# 列ベクトル: 2行1列のArrayを定義
w = [5.0, 3.0]

# 行ベクトル: 1行2列
x = [1.0 5.0]

# 内積の計算
xw = x * w

ベクトル w) 形: (2,), 型:Float64
[5.0, 3.0]

ベクトル x) 形: (1, 2), 型:Float64
[5.0 3.0]

ベクトル x_zeros) 形: (1, 5), 型:Float64
[0.0 0.0 0.0 0.0 0.0]

ベクトル x_ones) 形: (1, 5), 型:Float64
[1.0 1.0 1.0 1.0 1.0]

ベクトル uniform) 形: (1, 5), 型:Float64
[0.5908446386657102 0.7667970365022592 0.5662374165061859 0.4600853424625171 0.7940257103317943]

ベクトル normal) 形: (1, 5), 型:Float64
[2.2118774995743475 0.5328132821695382 -0.27173539603462066 0.5023344963886675 -0.5169836206932686]



1-element Array{Float64,1}:
 20.0

---

*This notebook was generated using [Literate.jl](https://github.com/fredrikekre/Literate.jl).*