In [1]:
using Pkg; Pkg.activate("."); Pkg.instantiate()

 Activating environment at `/tmpdir/notebook/Project.toml`


# Chapter 3 - 数学のおさらい

## 3.1 線形代数
### 3.1.1 スカラーとベクトル

In [2]:
# 列ベクトル: 2行1列のArrayを定義
# Juliaはcolumn-major
w = [5.0, 3.0]


# 行ベクトル

2-element Array{Float64,1}:
 5.0
 3.0

In [3]:
# 行ベクトル: 1行2列
x = [5.0 3.0]

1×2 Array{Float64,2}:
 5.0  3.0

In [4]:
# すべての要素が0の1行5列のArrayを生成
x_zeros = zeros(1, 5)

1×5 Array{Float64,2}:
 0.0  0.0  0.0  0.0  0.0

In [5]:
# すべての要素が1の1行5列のArrayを生成
x_ones = ones(1, 5)

1×5 Array{Float64,2}:
 1.0  1.0  1.0  1.0  1.0

In [6]:
# 一様分布または正規分布にしたがってランダムに1行5列のArrayを生成
using Random
Random.seed!(1234)

# 一様分布
uniform = rand(1, 5)

1×5 Array{Float64,2}:
 0.590845  0.766797  0.566237  0.460085  0.794026

In [7]:
# 正規分布
normal = randn(1, 5)

1×5 Array{Float64,2}:
 2.21188  0.532813  -0.271735  0.502334  -0.516984

In [8]:
# 標準出力
for s in (:w, :x, :x_zeros, :x_ones, :uniform, :normal)
    y = eval(s)
    println("ベクトル $(s)) 形: $(size(y)), 要素の型:$(eltype(y))\n$(y)\n")
end


### 3.1.2 ベクトルの内積
# 列ベクトル: 2行1列のArrayを定義
w = [5.0, 3.0]

# 行ベクトル: 1行2列
x = [1.0 5.0]

# 内積の計算
# \cdot
using LinearAlgebra
xw = x ⋅ w

ベクトル w) 形: (2,), 要素の型:Float64
[5.0, 3.0]

ベクトル x) 形: (1, 2), 要素の型:Float64
[5.0 3.0]

ベクトル x_zeros) 形: (1, 5), 要素の型:Float64
[0.0 0.0 0.0 0.0 0.0]

ベクトル x_ones) 形: (1, 5), 要素の型:Float64
[1.0 1.0 1.0 1.0 1.0]

ベクトル uniform) 形: (1, 5), 要素の型:Float64
[0.5908446386657102 0.7667970365022592 0.5662374165061859 0.4600853424625171 0.7940257103317943]

ベクトル normal) 形: (1, 5), 要素の型:Float64
[2.2118774995743475 0.5328132821695382 -0.27173539603462066 0.5023344963886675 -0.5169836206932686]



20.0

In [9]:
# wのノルムの計算: wの転置(行ベクトル)とw(列ベクトル)の掛け算
ww = transpose(w) ⋅ w

34.0

In [10]:
# ノルムを計算する関数が用意されている
norm(w)

5.830951894845301

In [11]:
println("xとwの内積) 形: $(size(xw)), 型:$(typeof(xw))\n$(xw)\n")
println("wのノルム) 形: $(size(ww)), 型:$(typeof(ww))\n$(ww)\n")

xとwの内積) 形: (), 型:Float64
20.0

wのノルム) 形: (), 型:Float64
34.0



### 3.1.5 行列とベクトルの関係

In [12]:
# 行列: 3行2列のArrayを定義
X = [1.0 2.0; 2.0 4.0; 3.0 6.0]

3×2 Array{Float64,2}:
 1.0  2.0
 2.0  4.0
 3.0  6.0

In [13]:
# 1行目の行ベクトル(1行2列)の取り出し
Xrow1 = X[[1], :]

1×2 Array{Float64,2}:
 1.0  2.0

In [14]:
# 2列目の列ベクトル(3行1列)の取り出し
Xcol2 = X[:, [2]]

3×1 Array{Float64,2}:
 2.0
 4.0
 6.0

In [15]:
# 標準出力
println("行列X) 形:$(size(X)), 要素の型:$(eltype(X))\n$(X)\n")
println("1行目) 形:$(size(Xrow1)), 要素の型:$(eltype(Xrow1))\n$(Xrow1)\n")
println("2列目) 形:$(size(Xcol2)), 要素の型:$(eltype(Xcol2))\n$(Xcol2)\n")

行列X) 形:(3, 2), 要素の型:Float64
[1.0 2.0; 2.0 4.0; 3.0 6.0]

1行目) 形:(1, 2), 要素の型:Float64
[1.0 2.0]

2列目) 形:(3, 1), 要素の型:Float64
[2.0; 4.0; 6.0]



In [16]:
# リストなしの場合
X[1, :]

2-element Array{Float64,1}:
 1.0
 2.0

In [17]:
# リストありの場合
X[[1], :]

1×2 Array{Float64,2}:
 1.0  2.0

### 3.1.6 行列の積と和

In [18]:
# 行列 X: 3行2列のArrayを定義
X = [1.0 2.0; 2.0 4.0; 3.0 6.0]

# 列ベクトル b: 2行1列のArrayを定義
w = [5.0, 3.0]

# 列ベクトル b: 3行1列のArrayを定義
b = [1.0, 1.0, 1.0]

# 行列とベクトルの積と和
res = X * w .+ b
println("積和の結果 \n$(res)")

積和の結果 
[12.0, 23.0, 34.0]


### 3.1.8 行列の階数

In [19]:
# 行列: 2行2列のArrayを定義
A = [6.0 2.0; 2.0 5.0]
B = [6.0 3.0; 2.0 1.0]

# 行列のランクの計算
println("Rank of A: $(rank(A))")
println("Rank of B: $(rank(B))")

Rank of A: 2
Rank of B: 1


In [20]:
function find_inv(mat)
    if rank(mat) == size(mat)[1]
        println("行列:\n$(mat)\nランク$(rank(mat))\n逆行列:\n$(inv(mat))\n")
    else
        println("行列:\n$(mat)\nランク$(rank(mat))\n特異行列")
    end
end

find_inv(A)
find_inv(B)

行列:
[6.0 2.0; 2.0 5.0]
ランク2
逆行列:
[0.1923076923076923 -0.07692307692307693; -0.07692307692307693 0.23076923076923078]

行列:
[6.0 3.0; 2.0 1.0]
ランク1
特異行列


### 3.1.10 行列と行列式の関係

In [21]:
# 行列: 2行2列のArrayを定義
A = [6.0 2.0; 2.0 5.0]
B = [6.0 3.0; 2.0 1.0]

# 行列式の計算
println("行列Aの行列式: $(det(A))")
println("行列Bの行列式: $(det(B))")

行列Aの行列式: 26.0
行列Bの行列式: 0.0


### 3.1.12 固有値問題の解法

In [22]:
# 行列Aの定義
A = [3 2; 4 1]

# 固有値問題の解
eig_A = eigen(A)

LinearAlgebra.Eigen{Float64,Float64,Array{Float64,2},Array{Float64,1}}
values:
2-element Array{Float64,1}:
 -1.0
  5.0
vectors:
2×2 Array{Float64,2}:
 -0.447214  0.707107
  0.894427  0.707107

### 3.1.13 固有値と固有ベクトルの性質

In [23]:
# 行列Aの定義
A = [3 1; 1 3]

# 固有値・固有ベクトル
eig_A = eigen(A)

println("行列Aの固有値:\n$(eig_A.values)")
println("行列Aの固有ベクトル:\n$(eig_A.vectors)")
println("固有ベクトルの内積:$(eig_A.vectors[:, 1] ⋅ eig_A.vectors[:, 2])")
println("固有値の和:$(sum(eig_A.values))")
println("行列Aのトレース(対角成分の和):$(tr(A))")
println("固有値の積:$(prod(eig_A.values))")
println("行列Aの行列式:$(det(A))")
println("固有ベクトルがなす行列の逆行列:\n$(eig_A.vectors)")
println("固有ベクトルがなす行列の転置行列:\n$(eig_A.vectors')")

行列Aの固有値:
[2.0, 4.0]
行列Aの固有ベクトル:
[-0.7071067811865475 0.7071067811865475; 0.7071067811865475 0.7071067811865475]
固有ベクトルの内積:0.0
固有値の和:6.0
行列Aのトレース(対角成分の和):6
固有値の積:8.0
行列Aの行列式:8.0
固有ベクトルがなす行列の逆行列:
[-0.7071067811865475 0.7071067811865475; 0.7071067811865475 0.7071067811865475]
固有ベクトルがなす行列の転置行列:
[-0.7071067811865475 0.7071067811865475; 0.7071067811865475 0.7071067811865475]


## 3.2 最適化

In [24]:
# 行列Aの定義
A = [2 -3; 4 1]

# 列ベクトルbの定義
b = [5, -2]

2-element Array{Int64,1}:
  5
 -2

In [25]:
# 行列が非ゼロか否かを確認
if det(A) != 0
    # Aの逆行列とベクトルbの積から解を求める
    w = inv(A) * b
    println("wの解\n$(w)")
else
    # 解が存在しない
    println("解が存在しません.")
end

wの解
[-0.07142857142857151, -1.714285714285714]


### 3.2.2 微分を用いた解放

In [26]:
# 最急降下法による最適化
# 学習率の設定
α = 0.2

# パラメーターの初期化
w = 1

for ite in 1:50
    println("反復$(ite), w=$(round(w; digits = 2))")
    # 最急降下法によるパラメーターの更新
    global w-= α * 3 * w^2
end

反復1, w=1.0
反復2, w=0.4
反復3, w=0.3
反復4, w=0.25
反復5, w=0.21
反復6, w=0.18
反復7, w=0.16
反復8, w=0.15
反復9, w=0.13
反復10, w=0.12
反復11, w=0.11
反復12, w=0.11
反復13, w=0.1
反復14, w=0.09
反復15, w=0.09
反復16, w=0.08
反復17, w=0.08
反復18, w=0.08
反復19, w=0.07
反復20, w=0.07
反復21, w=0.07
反復22, w=0.06
反復23, w=0.06
反復24, w=0.06
反復25, w=0.06
反復26, w=0.06
反復27, w=0.05
反復28, w=0.05
反復29, w=0.05
反復30, w=0.05
反復31, w=0.05
反復32, w=0.05
反復33, w=0.04
反復34, w=0.04
反復35, w=0.04
反復36, w=0.04
反復37, w=0.04
反復38, w=0.04
反復39, w=0.04
反復40, w=0.04
反復41, w=0.04
反復42, w=0.04
反復43, w=0.03
反復44, w=0.03
反復45, w=0.03
反復46, w=0.03
反復47, w=0.03
反復48, w=0.03
反復49, w=0.03
反復50, w=0.03


In [27]:
### 3.3.2 ベルヌーイ分布
# p=6/13(青色のボールの確率)のベルヌーイ分布に従って10回試行を行う
using Distributions

b = Bernoulli(6/13)

X1 = rand(b, 10)
X2 = rand(b, 10)
X3 = rand(b, 10)

# 標準出力
println("データ X1:\n$(X1)")
println("データ X2:\n$(X2)")
println("データ X3:\n$(X3)")


### 3.3.9 正規分布
# 平均0, 分散1の正規分布に従って10回試行を行う
X1 = rand(Normal(0, 1), 10)
# 平均3, 分散1の正規分布に従って10回試行を行う
X2 = rand(Normal(3, 1), 10)
# 平均-3, 分散1の正規分布に従って10回試行を行う
X3 = rand(Normal(-3, 1), 10)

# 標準出力
println("データ X1:\n$(X1)")
println("データ X2:\n$(X2)")
println("データ X3:\n$(X3)")

データ X1:
Bool[0, 1, 1, 0, 0, 1, 1, 0, 1, 0]
データ X2:
Bool[0, 0, 0, 0, 0, 1, 1, 1, 1, 1]
データ X3:
Bool[0, 1, 1, 1, 1, 0, 0, 1, 1, 0]
データ X1:
[-0.0801624859452718, -1.0912192142639132, -0.5805165450434235, -0.3154372460983286, -1.3614476249361172, -0.11445720023473198, 0.1658369675157237, -0.40843803219265074, -1.009783518501397, -0.5438048486401967]
データ X2:
[1.7732752739906517, 2.4582842802456284, 2.3135064634858282, 2.287068038497515, 2.672941103913246, 3.5148361669491317, 5.417473347868045, 2.6920263400560214, 4.245303385857344, 2.9500497686966383]
データ X3:
[-4.054777824036921, -3.9871768159072896, -1.5178276320266384, -3.5227721501159825, -4.580700774609182, -2.868157669702522, -2.552642042695429, -3.3962106846886626, -2.6332267441869477, -2.3783267445521994]


## 3.4 統計
### 3.4.1 中心の統計量

In [28]:
# 3種類(身長、体重、胸囲)のデータを格納する8行3列の行列
X = [
    170 60 80;
    167 52 93;
    174 57 85;
    181 70 80;
    171 62 70;
    171 66 95;
    171 66 95;
    168 54 85;
]

# 行方向(dims=1)に対して、平均値を計算
means = mean(X; dims=1)

# 行方向(dims=1)に対して、中央値を計算
medians = median(X; dims=1)

# 標準出力
println("データ X:\n$X")
println("身長の平均値: $(means[1]), 体重の平均値:$(means[2]), 胸囲の平均値$(means[3])")
println("身長の中央値: $(medians[1]), 体重の中央値:$(medians[2]), 胸囲の中央値$(medians[3])")


# src

データ X:
[170 60 80; 167 52 93; 174 57 85; 181 70 80; 171 62 70; 171 66 95; 171 66 95; 168 54 85]
身長の平均値: 171.625, 体重の平均値:60.875, 胸囲の平均値85.375
身長の中央値: 171.0, 体重の中央値:61.0, 胸囲の中央値85.0


In [29]:
# 分散共分散行列の計算
# 3種類(身長、体重、胸囲)のデータを格納する8行3列の行列
X = [
    170 60 80;
    167 52 93;
    174 57 85;
    181 70 80;
    171 62 70;
    171 66 95;
    171 66 95;
    168 54 85;
]
vars = var(X; corrected=false, dims=1)
stds = std(X; corrected=false, dims=1)
cov_bias = cov(X)
cov_nobias = cov(X; corrected=false)
println("データ X:\n$X")
println("分散) 身長:$(vars[1]), 体重:$(vars[2]), 胸囲:$(vars[3])")
println("標準偏差) 身長:$(stds[1]), 体重:$(stds[2]), 胸囲:$(stds[3])")
println("分散共分散行列 バイアスあり:\n$(cov_bias)")
println("分散共分散行列 バイアスなし:\n$(cov_nobias)")

データ X:
[170 60 80; 167 52 93; 174 57 85; 181 70 80; 171 62 70; 171 66 95; 171 66 95; 168 54 85]
分散) 身長:16.484375, 体重:34.859375, 胸囲:67.234375
標準偏差) 身長:4.0600954422279285, 体重:5.9041828393097715, 胸囲:8.199657005021612
分散共分散行列 バイアスあり:
[18.83928571428571 19.517857142857142 -11.267857142857142; 19.517857142857142 39.839285714285715 -3.8035714285714284; -11.267857142857142 -3.8035714285714284 76.83928571428571]
分散共分散行列 バイアスなし:
[16.484375 17.078125 -9.859375; 17.078125 34.859375 -3.328125; -9.859375 -3.328125 67.234375]


### 3.4.7 相関係数と相関行列

In [30]:
# 3種類(身長、体重、胸囲)のデータを格納する8行3列の行列
X = [
    170 60 80;
    167 52 93;
    174 57 85;
    181 70 80;
    171 62 70;
    171 66 95;
    171 66 95;
    168 54 85;
]
println("データ X:\n$X")
println("相関行列:\n$(cor(X))")

データ X:
[170 60 80; 167 52 93; 174 57 85; 181 70 80; 171 62 70; 171 66 95; 171 66 95; 168 54 85]
相関行列:
[1.0 0.7124331954587388 -0.2961539001511891; 0.7124331954587388 1.0 -0.06874547945864228; -0.2961539001511891 -0.06874547945864228 1.0]


---

*This notebook was generated using [Literate.jl](https://github.com/fredrikekre/Literate.jl).*