In [1]:
using Pkg; Pkg.activate("."); Pkg.instantiate()

 Activating environment at `/tmpdir/notebook/Project.toml`


# Chapter 3 - 数学のおさらい

## 3.1
### 3.1.1 スカラーとベクトル

In [2]:
# 列ベクトル: 2行1列のArrayを定義
# Juliaはcolumn-major
w = [5.0, 3.0]


# 行ベクトル

2-element Array{Float64,1}:
 5.0
 3.0

In [3]:
# 行ベクトル: 1行2列
x = [5.0 3.0]

1×2 Array{Float64,2}:
 5.0  3.0

In [4]:
# すべての要素が0の1行5列のArrayを生成
x_zeros = zeros(1, 5)

1×5 Array{Float64,2}:
 0.0  0.0  0.0  0.0  0.0

In [5]:
# すべての要素が1の1行5列のArrayを生成
x_ones = ones(1, 5)

1×5 Array{Float64,2}:
 1.0  1.0  1.0  1.0  1.0

In [6]:
# 一様分布または正規分布にしたがってランダムに1行5列のArrayを生成
using Random
Random.seed!(1234)

# 一様分布
uniform = rand(1, 5)

1×5 Array{Float64,2}:
 0.590845  0.766797  0.566237  0.460085  0.794026

In [7]:
# 正規分布
normal = randn(1, 5)

1×5 Array{Float64,2}:
 2.21188  0.532813  -0.271735  0.502334  -0.516984

In [8]:
# 標準出力
for s in (:w, :x, :x_zeros, :x_ones, :uniform, :normal)
    y = eval(s)
    println("ベクトル $(s)) 形: $(size(y)), 要素の型:$(eltype(y))\n$(y)\n")
end


### 3.1.2 ベクトルの内積
# 列ベクトル: 2行1列のArrayを定義
w = [5.0, 3.0]

# 行ベクトル: 1行2列
x = [1.0 5.0]

# 内積の計算
using LinearAlgebra
xw = x ⋅ w

ベクトル w) 形: (2,), 要素の型:Float64
[5.0, 3.0]

ベクトル x) 形: (1, 2), 要素の型:Float64
[5.0 3.0]

ベクトル x_zeros) 形: (1, 5), 要素の型:Float64
[0.0 0.0 0.0 0.0 0.0]

ベクトル x_ones) 形: (1, 5), 要素の型:Float64
[1.0 1.0 1.0 1.0 1.0]

ベクトル uniform) 形: (1, 5), 要素の型:Float64
[0.5908446386657102 0.7667970365022592 0.5662374165061859 0.4600853424625171 0.7940257103317943]

ベクトル normal) 形: (1, 5), 要素の型:Float64
[2.2118774995743475 0.5328132821695382 -0.27173539603462066 0.5023344963886675 -0.5169836206932686]



20.0

In [9]:
# wのノルムの計算: wの転置(行ベクトル)とw(列ベクトル)の掛け算
ww = transpose(w) ⋅ w

34.0

In [10]:
# ノルムを計算する関数が用意されている
norm(w)

5.830951894845301

In [11]:
println("xとwの内積) 形: $(size(xw)), 型:$(typeof(xw))\n$(xw)\n")
println("wのノルム) 形: $(size(ww)), 型:$(typeof(ww))\n$(ww)\n")

xとwの内積) 形: (), 型:Float64
20.0

wのノルム) 形: (), 型:Float64
34.0



### 3.1.5 行列とベクトルの関係

In [12]:
# 行列: 3行2列のArrayを定義
X = [1.0 2.0; 2.0 4.0; 3.0 6.0]

3×2 Array{Float64,2}:
 1.0  2.0
 2.0  4.0
 3.0  6.0

In [13]:
# 1行目の行ベクトル(1行2列)の取り出し
Xrow1 = X[[1], :]

1×2 Array{Float64,2}:
 1.0  2.0

In [14]:
# 2列目の列ベクトル(3行1列)の取り出し
Xcol2 = X[:, [2]]

3×1 Array{Float64,2}:
 2.0
 4.0
 6.0

In [15]:
# 標準出力
println("行列X) 形:$(size(X)), 要素の型:$(eltype(X))\n$(X)\n")
println("1行目) 形:$(size(Xrow1)), 要素の型:$(eltype(Xrow1))\n$(Xrow1)\n")
println("2列目) 形:$(size(Xcol2)), 要素の型:$(eltype(Xcol2))\n$(Xcol2)\n")

行列X) 形:(3, 2), 要素の型:Float64
[1.0 2.0; 2.0 4.0; 3.0 6.0]

1行目) 形:(1, 2), 要素の型:Float64
[1.0 2.0]

2列目) 形:(3, 1), 要素の型:Float64
[2.0; 4.0; 6.0]



In [16]:
# リストなしの場合
X[1, :]

2-element Array{Float64,1}:
 1.0
 2.0

In [17]:
# リストありの場合
X[[1], :]

1×2 Array{Float64,2}:
 1.0  2.0

### 3.1.6 行列の積と和

In [18]:
# 行列 X: 3行2列のArrayを定義
X = [1.0 2.0; 2.0 4.0; 3.0 6.0]

# 列ベクトル b: 2行1列のArrayを定義
w = [5.0, 3.0]

# 列ベクトル b: 3行1列のArrayを定義
b = [1.0, 1.0, 1.0]

# 行列とベクトルの積と和
res = X * w .+ b
println("積和の結果 \n$(res)")

積和の結果 
[12.0, 23.0, 34.0]


### 3.1.8 行列の階数

In [19]:
# 行列: 2行2列のArrayを定義
A = [6.0 2.0; 2.0 5.0]
B = [6.0 3.0; 2.0 1.0]

# 行列のランクの計算
println("Rank of A: $(rank(A))")
println("Rank of B: $(rank(B))")

Rank of A: 2
Rank of B: 1


In [20]:
function find_inv(mat)
    if rank(mat) == size(mat)[1]
        println("行列:\n$(mat)\nランク$(rank(mat))\n逆行列:\n$(inv(mat))\n")
    else
        println("行列:\n$(mat)\nランク$(rank(mat))\n特異行列")
    end
end

find_inv(A)
find_inv(B)

行列:
[6.0 2.0; 2.0 5.0]
ランク2
逆行列:
[0.1923076923076923 -0.07692307692307693; -0.07692307692307693 0.23076923076923078]

行列:
[6.0 3.0; 2.0 1.0]
ランク1
特異行列


---

*This notebook was generated using [Literate.jl](https://github.com/fredrikekre/Literate.jl).*